import { Event, User } from './types'

export const mockUser: User = {
  id: 'user-1',
  name: 'Alex Wijaya',
  avatar: '👤',
  bio: 'Love gaming and outdoor sports',
  eventsCreated: 3,
  eventsJoined: 12,
  rating: 4.8,
}

export const mockEvents: Event[] = [
  {
    id: 'event-1',
    title: 'Mobile Legends Tournament',
    description:
      'Competitive gaming session for Mobile Legends. Looking for skilled players. Bring your A-game!',
    category: 'gaming',
    date: new Date(2024, 11, 15),
    time: '19:00',
    location: 'Gaming Cafe Downtown',
    address: 'Jl. Gatot Subroto No. 123, Jakarta',
    maxParticipants: 5,
    currentParticipants: 3,
    status: 'open',
    creatorId: 'user-2',
    creatorName: 'Budi Rahman',
    image: '🎮',
    tags: ['competitive', 'mobile-legends', 'tournament'],
    requiresApproval: false,
    participants: [
      {
        id: 'p-1',
        userId: 'user-1',
        userName: 'Alex Wijaya',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-2',
        userId: 'user-3',
        userName: 'Citra Lestari',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-3',
        userId: 'user-4',
        userName: 'Dimas Pratama',
        status: 'pending',
        joinedAt: new Date(),
      },
    ],
    createdAt: new Date(),
  },
  {
    id: 'event-2',
    title: 'Basketball Game - 5v5',
    description:
      'Casual 5v5 basketball game at Senayan court. All skill levels welcome. We provide balls and cones.',
    category: 'sports',
    date: new Date(2024, 11, 16),
    time: '17:30',
    location: 'Senayan Basketball Court',
    address: 'Jl. Gelora Bung Karno, Jakarta',
    maxParticipants: 10,
    currentParticipants: 7,
    status: 'open',
    creatorId: 'user-5',
    creatorName: 'Rian Gunawan',
    image: '🏀',
    tags: ['basketball', 'casual', '5v5'],
    requiresApproval: true,
    participants: [
      {
        id: 'p-4',
        userId: 'user-1',
        userName: 'Alex Wijaya',
        status: 'pending',
        joinedAt: new Date(),
      },
      {
        id: 'p-5',
        userId: 'user-6',
        userName: 'Siti Nurhaliza',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-6',
        userId: 'user-7',
        userName: 'Taufik Hidayat',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-7',
        userId: 'user-8',
        userName: 'Elisa Amanda',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-8',
        userId: 'user-9',
        userName: 'Fajar Setiawan',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-9',
        userId: 'user-10',
        userName: 'Gita Wirawan',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-10',
        userId: 'user-11',
        userName: 'Hendra Kusuma',
        status: 'joined',
        joinedAt: new Date(),
      },
    ],
    createdAt: new Date(),
  },
  {
    id: 'event-3',
    title: 'Morning Gym Session',
    description:
      'Group fitness class: cardio and strength training. Beginner-friendly. We meet every Wednesday morning.',
    category: 'fitness',
    date: new Date(2024, 11, 13),
    time: '06:30',
    location: 'Fitness Plus Gym',
    address: 'Jl. Sudirman No. 456, Jakarta',
    maxParticipants: 20,
    currentParticipants: 12,
    status: 'open',
    creatorId: 'user-12',
    creatorName: 'Nadya Fitri',
    image: '💪',
    tags: ['fitness', 'gym', 'cardio'],
    requiresApproval: false,
    participants: [
      {
        id: 'p-11',
        userId: 'user-1',
        userName: 'Alex Wijaya',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-12',
        userId: 'user-13',
        userName: 'Olivia Chen',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-13',
        userId: 'user-14',
        userName: 'Petra Volkov',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-14',
        userId: 'user-15',
        userName: 'Qasim Ahmad',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-15',
        userId: 'user-16',
        userName: 'Rita Suryani',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-16',
        userId: 'user-17',
        userName: 'Sasha Ivanov',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-17',
        userId: 'user-18',
        userName: 'Tania Kowalski',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-18',
        userId: 'user-19',
        userName: 'Ulvi Pasha',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-19',
        userId: 'user-20',
        userName: 'Vanya Petrov',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-20',
        userId: 'user-21',
        userName: 'Windy Salim',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-21',
        userId: 'user-22',
        userName: 'Xander Tong',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-22',
        userId: 'user-23',
        userName: 'Yasmin Mustafa',
        status: 'joined',
        joinedAt: new Date(),
      },
    ],
    createdAt: new Date(),
  },
  {
    id: 'event-4',
    title: 'Board Game Hangout',
    description:
      'Chill hangout with board games: Catan, Ticket to Ride, and more. Drinks and snacks provided.',
    category: 'hangout',
    date: new Date(2024, 11, 14),
    time: '19:00',
    location: 'Board Game Lounge',
    address: 'Jl. Kemang Raya No. 789, Jakarta',
    maxParticipants: 8,
    currentParticipants: 5,
    status: 'open',
    creatorId: 'user-24',
    creatorName: 'Zara Mahendra',
    image: '🎲',
    tags: ['board-games', 'hangout', 'casual'],
    requiresApproval: false,
    participants: [
      {
        id: 'p-23',
        userId: 'user-1',
        userName: 'Alex Wijaya',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-24',
        userId: 'user-25',
        userName: 'Angga Kusuma',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-25',
        userId: 'user-26',
        userName: 'Bella Santoso',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-26',
        userId: 'user-27',
        userName: 'Cahya Dwiputra',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-27',
        userId: 'user-28',
        userName: 'Desy Ratnawati',
        status: 'joined',
        joinedAt: new Date(),
      },
    ],
    createdAt: new Date(),
  },
  {
    id: 'event-5',
    title: 'Badminton Double Tournament',
    description:
      'Friendly doubles badminton tournament. Matches best of 3. Rackets provided if needed.',
    category: 'sports',
    date: new Date(2024, 11, 17),
    time: '18:00',
    location: 'Badminton Court Blok M',
    address: 'Jl. Melawai No. 321, Jakarta',
    maxParticipants: 8,
    currentParticipants: 6,
    status: 'open',
    creatorId: 'user-29',
    creatorName: 'Fabian Sartori',
    image: '🏸',
    tags: ['badminton', 'doubles', 'tournament'],
    requiresApproval: true,
    participants: [
      {
        id: 'p-28',
        userId: 'user-1',
        userName: 'Alex Wijaya',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-29',
        userId: 'user-30',
        userName: 'Giona Gabriela',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-30',
        userId: 'user-31',
        userName: 'Hendro Sutanto',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-31',
        userId: 'user-32',
        userName: 'Intan Wijaya',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-32',
        userId: 'user-33',
        userName: 'Jojo Tanyasto',
        status: 'joined',
        joinedAt: new Date(),
      },
      {
        id: 'p-33',
        userId: 'user-34',
        userName: 'Krisna Andhara',
        status: 'joined',
        joinedAt: new Date(),
      },
    ],
    createdAt: new Date(),
  },
]
